version: '3.3'
services:
    web:
        build: .
        ports:
            - "80:8000"
        env_file:
            - .env
        command: ["./kullaniciservisi"]

    migrations:
        build:
            context: .
            dockerfile: Dockerfile.migrations
        depends_on:
            - database
        env_file:
            - .env
        command: ["./postgresql.sh"]

    database:
        image: postgres
        environment:
            - POSTGRES_USER=sinan
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=kullanici
        volumes:
            - ar-pgdata:/var/lib/postgresql/data

volumes:
    ar-pgdata:
